spring:
  h2:
    console:
      enabled: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/
logging:
  level:
    root: INFO
    com.feiniaojin: DEBUG
hikari:
  db0:
    minimum-idle: 4
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: db0
    max-lifetime: 1800000
    connection-timeout: 10000
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    #启动时需要初始化的建表语句
    schema:
      - classpath*:schema.sql
    #初始化的数据
    data: classpath*:data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    continue-on-error: false
    sql-script-encoding: utf-8
  db1:
    minimum-idle: 4
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: db1
    max-lifetime: 1800000
    connection-timeout: 10000
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    #启动时需要初始化的建表语句
    schema:
      - classpath*:schema.sql
    #初始化的数据
    data: classpath*:data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    continue-on-error: false
    sql-script-encoding: utf-8
  db2:
    minimum-idle: 4
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: db1
    max-lifetime: 1800000
    connection-timeout: 10000
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    #启动时需要初始化的建表语句
    schema:
      - classpath*:schema.sql
    #初始化的数据
    data: classpath*:data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    continue-on-error: false
    sql-script-encoding: utf-8
  db3:
    minimum-idle: 4
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: db1
    max-lifetime: 1800000
    connection-timeout: 10000
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    #启动时需要初始化的建表语句
    schema:
      - classpath*:schema.sql
    #初始化的数据
    data: classpath*:data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    continue-on-error: false
    sql-script-encoding: utf-8
  db4:
    minimum-idle: 4
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: db1
    max-lifetime: 1800000
    connection-timeout: 10000
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    #启动时需要初始化的建表语句
    schema:
      - classpath*:schema.sql
    #初始化的数据
    data: classpath*:data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    continue-on-error: false
    sql-script-encoding: utf-8
  db5:
    minimum-idle: 4
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: db1
    max-lifetime: 1800000
    connection-timeout: 10000
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    #启动时需要初始化的建表语句
    schema:
      - classpath*:schema.sql
    #初始化的数据
    data: classpath*:data.sql
    # Initialize the datasource with available DDL and DML scripts.
    initialization-mode: always
    continue-on-error: false
    sql-script-encoding: utf-8